targetSystem: "linux"
datadog:
  apiKeyExistingSecret: <DATADOG_API_KEY_SECRET>
  appKeyExistingSecret: <DATADOG_APP_KEY_SECRET>
  clusterName: <CLUSTER_NAME>
  tags: []
  logs:
    enabled: true
    containerCollectAll: false
    containerCollectUsingFiles: true
  apm:
    portEnabled: true
    socketPath: /var/run/datadog/apm.socket
    hostSocketPath: /var/run/datadog/
  processAgent:
    enabled: true
    processCollection: false
  systemProbe:
    enableTCPQueueLength: false
    enableOOMKill: true
    collectDNSStats: false
